[package]
org= "ballerinax"
name= "googleapis.calendar"
version= "1.0.1"
export= ["googleapis.calendar", "googleapis.calendar.listener"]
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["google", "calendar"]
repository = "https://github.com/ballerina-platform/module-ballerinax-googleapis.calendar"

[[platform.java11.dependency]]
path = "../java-wrapper/build/libs/java-wrapper-1.0.1.jar"
groupId = "org.ballerinalang.googleapis.calendar"
artifactId = "java-wrapper"
version = "1.0.1"
